### PR TITLE
ADDR-109: Upgrading ConfigDirUtil.

### PR DESCRIPTION
**Pull request by mks-d**
@mseaton, this PR comes AH doesn't depend yet on the Initializer module. So for now there is a class that lives in a AH as a copy of the original from Iniz (`ConfigDirUtil` to name it).
Roughly the change here is that the checksums are managed in a separate directory, making the management of possible configuration overrides a lot easier and clearer.

### CODE REVIEW

**Comment by mseaton** [comment]
@mks-d , looks fine to me in principle.  All of the modifications are to classes that you added in an earlier commit, to support loading configuration from file, right?  I'm happy to follow your lead on that, and address any issues post-commit if they arise.  @mogoodrich any thoughts or objections?

**Comment by dkayiwa** [comment]
@mks-d do you have any response to @mseaton 's question above? "All of the modifications are to classes that you added in an earlier commit, to support loading configuration from file, right?"

**Comment by dkayiwa** [comment]
@mogoodrich any thoughts or objections? 😊

**Comment by mogoodrich** [comment]
I haven't had a chance to look in details, but if these are all changes to files  @mks-d added in a earlier commit (to the question asked by @mseaton), I'm fine with merging this in.

**Comment by dkayiwa** [comment]
Thanks @mogoodrich for the response. 😊 

So @mks-d if you can respond to the above, we are good to go.

**Comment by mks-d** [comment]
>All of the modifications are to classes that you added in an earlier commit, to support loading configuration from file, right?

Correct!

**Pull request merged**
