### PR TITLE
Escaping html on all admin pages

### PR DESCRIPTION
**Pull request by rkorytkowski**
## Issue I worked on

see https://openmrs.atlassian.net/browse/ADDR-

## Checklist: I completed these to help reviewers :)

- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by mogoodrich** [comment]
Thanks @rkorytkowski !

**Comment by icrc-fdeniger** [comment]
Hello @rkorytkowski  @mogoodrich  it seems that after this modification some levels are no more displayed on admin.

version the version 2.17.0 we have:
image
But with version 2.18.0:
image

the entries for `City/Village`, `State/Province`, `Postal Code` and `Address` are no more available ( same address template).
I suppose it's due to some chars like `/` or ` ` but I don't understand for Address`

**Comment by dkayiwa** [comment]
Which openmrs core version are you running?

**Comment by icrc-fdeniger** [comment]
2.5.14
we'd like to upgrade but not yet possible

**Comment by dkayiwa** [comment]
Do you mind sharing all the address hierarchy configs such that i use them to reproduce it locally? Or if you can just reproduce it on https://qa-refapp.openmrs.org/, that would be enough.

**Comment by icrc-fdeniger** [comment]
this our Address template:

```xml
              &lt;org.openmrs.layout.address.AddressTemplate&gt;
                  &lt;nameMappings class="properties"&gt;
                      &lt;property name="country" value="Location.country"/&gt;
                      &lt;property name="stateProvince" value="Location.stateProvince"/&gt;
                      &lt;property name="countyDistrict" value="Location.district"/&gt;
                      &lt;property name="cityVillage" value="Location.cityVillage"/&gt;
                      &lt;property name="address1" value="Location.address1"/&gt;
                      &lt;property name="address2" value="Location.address2"/&gt;
                      &lt;property name="postalCode" value="Location.postalCode"/&gt;
                  &lt;/nameMappings&gt;
                  &lt;sizeMappings class="properties"&gt;
                      &lt;property name="country" value="20"/&gt;
                      &lt;property name="stateProvince" value="20"/&gt;
                      &lt;property name="cityVillage" value="20"/&gt;
                      &lt;property name="address1" value="40"/&gt;
                      &lt;property name="address2" value="40"/&gt;
                      &lt;property name="postalCode" value="10"/&gt;
                      &lt;property name="countyDistrict" value="40"/&gt;
                  &lt;/sizeMappings&gt;
                  &lt;lineByLineFormat&gt;
                      &lt;string&gt;address1&lt;/string&gt;
                      &lt;string&gt;address2&lt;/string&gt;
                      &lt;string&gt;cityVillage postalCode&lt;/string&gt;
                      &lt;string&gt;countyDistrict&lt;/string&gt;
                      &lt;string&gt;stateProvince&lt;/string&gt;
                      &lt;string&gt;country&lt;/string&gt;
                  &lt;/lineByLineFormat&gt;
              &lt;/org.openmrs.layout.address.AddressTemplate&gt;
```

**Comment by dkayiwa** [comment]
With that address template, are you able to reproduce it here? https://qa-refapp.openmrs.org/

**Comment by icrc-fdeniger** [comment]
Yes just did a test here:
image
image

**Comment by dkayiwa** [comment]
Thanks @icrc-fdeniger for reporting this with a clearly defined way of reproducing it. I have just fixed it and released version 1.21.0 of the module.

**Comment by icrc-fdeniger** [comment]
thanks a lot @dkayiwa

**Pull request merged**
