### PR TITLE
Fix the bug that breaks the Address Hierarchy on OpenMRS v1.11.4/1.11…

### PR DESCRIPTION
**Pull request by steliomo**
Hi,

I had this problem when I did upgrade my OpenMRS version from 1.9.2 to 1.11.4/1.11.5.

Cheers

### CODE REVIEW

**Comment by mogoodrich** [comment]
Thanks!  I will merge this in.  Any chance you could write up a ticket in JIRA (in the Address Hierarchy module) saying what the symptons were (is this in the Ref App registration workflow?  the legacy UI)?  Then I can mark it as fixed and run a release, so if others run into the same issue and search for it JIRA they can discover they just need to upgrade to the latest version.

It isnt possibly this issue, is it?

https://issues.openmrs.org/browse/ADDR-77

Thanks again!
Mark

**Comment by steliomo** [comment]
Thanks Mark I will follow your approach.
It was in the legacy UI, I've just write a comment in the JIRA case explaining what I did.
Cheers

**Comment by psbrandt** [comment]
@mogoodrich, since this is a different issue, should a new ticket be created in JIRA?

**Comment by Machabane** [comment]
@psbrandt is it a different issue?

**Comment by psbrandt** [comment]
I'm not sure, but I think it might be, since on [ADDR-77](https://issues.openmrs.org/browse/ADDR-77), [N A](https://issues.openmrs.org/secure/ViewProfile.jspa?name=nostalgicamigo) does not mention seeing a **Syntax Error** in the console, while @steliomo does.

One way we could confirm that it's the same issue would be to ask [N A](https://issues.openmrs.org/secure/ViewProfile.jspa?name=nostalgicamigo) to test @steliomo's fix.

**Comment by steliomo** [comment]
@psbrandt I think it is the same issue. I saw the error because I was inspecting the code in the browser.

**Comment by psbrandt** [comment]
@mogoodrich is there a roadmap for this module and/or a planned next release? If not, maybe we could work together to put out a patch release, since this is currently blocking us from upgrading to <kbd>1.11.x</kbd>.

**Comment by mogoodrich** [comment]
No roadmap, but we do releases ad hoc as needed.  I should be able to do one later this week, or feel free to do it yourself, if needed sooner.

**Comment by mogoodrich** [comment]
I just did a 2.9 release of address hierarchy with this fix.

**Comment by steliomo** [comment]
Great,

Thanks Mark

2016-06-18 14:22 GMT+02:00 Mark Goodrich <notifications@github.com>:

> I just did a 2.9 release of address hierarchy with this fix.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openmrs/openmrs-module-addresshierarchy/pull/11#issuecomment-226938663>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAYsGtC762LTdypuAOMxNnG44Piw2xH1ks5qM-MOgaJpZM4Iy3lH>
> .
>



-- 







*************************************************
************************************************Eng.º Stélio Moiane +(258)
82 2546100 <%2B258822546100>+(258) 84 0546824 <%2B258840546824>Software
Development Specialist*************************************************

**Pull request merged**
