### PR TITLE
ADDR-125: AddressHierarchyConstants.PATTERN_NON_WORD_AND_NON_WHITESPACE to be more specific and should not match non-alphanumeric words

### PR DESCRIPTION
**Pull request by Ruhanga**
Ticket: https://issues.openmrs.org/browse/ADDR-125

This PR basically allows for non-alphanumeric words to be searchable, words like កម្ពុជា.

### CODE REVIEW

**Review by mks-d — COMMENTED** [review]
@Ruhanga please associate this with the relevant KH ticket.

Will there be tests added in the final PR, presumably in `AddressHierarchyServiceTest`? Not sure if this was tested already...

**Comment by rbuisson** [comment]
This is the JIRA ticket: https://issues.openmrs.org/browse/ADDR-125

**Review by Ruhanga — COMMENTED** [review]
Thanks for the ticket @rbuisson, I'll associate it with this PR.

**Review by rbuisson — APPROVED** [review]

**Review by mks-d — APPROVED** [review]
@mogoodrich / @mseaton our early tests show that this seems to be fine, so in order to unlock the Cambodia project I'm merging this in.
Please let us know if you notice anything wrong in your bleeding edge envs.

**Comment by mogoodrich** [comment]
Sounds good, thanks @mks-d !

**Pull request merged**
