### PR TITLE
ADDR-62 Use Daemon to authenticate task instead of scheduler.username

### PR DESCRIPTION
**Pull request by dulvinw**
https://issues.openmrs.org/browse/ADDR-62

### CODE REVIEW

**Comment by gitcliff** [comment]
@dulvinw can u attach the link to ticket

**Comment by samuelmale** [comment]
Can we have some test coverage?

**Comment by dulvinw** [comment]
> @dulvinw can u attach the link to ticket

Hi This is the link to the issue. https://issues.openmrs.org/browse/ADDR-62

**Comment by dulvinw** [comment]
> Can we have some test coverage?

What do I have to get that information? Can you help me in getting that done?

**Comment by gitcliff** [comment]
@dulvinw the link to the ticket should appear in the title/summary section where its currently saying "No description provided." ie the link should appear in the title of your pull request as advice here https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dulvinw** [comment]
@gitcliff done.

**Comment by dkayiwa** [comment]
Have you actually compiled, installed the module, and tested this out in a running openmrs web application?

**Comment by dulvinw** [comment]
Yes I have and everything builds fine

**Comment by dulvinw** [comment]
Any update of the status @dkayiwa @gitcliff

**Pull request closed without merging**
